from tkinter import *
root=Tk()
root.title("Libby")
root.geometry('500x500')
ss5=StringVar()
ss5.set("Dude")
myL=Label(root,text="Libby")
myK=Label(root,textvariable=ss5)
#myL.pack()
def myCC():
    a=myE.get()
    ss5.set(a)
myE=Entry(root,fg="white",bg="black")
myE.grid(row=0,column=0,columnspan=3)
myL.grid(row=0,column=0)
myK.grid(row=1,column=1)
myB=Button(root,text="Submit",fg="white",bg="black",command=myCC)
myB.grid(row=2,column=1)
root.mainloop()
